# Generated by Django 5.0 on 2024-03-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0027_allinternbatchs_acceptallagriment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinternbatchs',
            name='countryCode',
            field=models.CharField(max_length=30),
        ),
    ]
