# Generated by Django 5.0 on 2024-03-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0029_allstudentdetails_productuser_referreldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinternbatchs',
            name='isInterviewSend',
            field=models.BooleanField(default=False),
        ),
    ]
