# Generated by Django 5.0 on 2024-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0030_allinternbatchs_isinterviewsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinternbatchs',
            name='sendHireMessage',
            field=models.BooleanField(default=False),
        ),
    ]
