# Generated by Django 5.0 on 2024-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0031_allinternbatchs_sendhiremessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBatchesInstractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=50)),
                ('Instractions', models.TextField(blank=True, null=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('startDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='referreldata',
            name='refrelList',
            field=models.JSONField(default={'listdata': []}),
        ),
    ]
