# Generated by Django 5.0 on 2024-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0031_allinternbatchs_sendhiremessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBatchesInstractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=50)),
                ('Instractions', models.TextField(blank=True, null=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('batchNameShow', models.CharField(default='', max_length=50)),
                ('batchPrice', models.IntegerField(default=0)),
                ('batchActive', models.BooleanField(default=True)),
                ('batchHide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCallRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('lastUpdateTime', models.TimeField(auto_now=True)),
                ('lastUpdateDate', models.DateField(auto_now=True)),
                ('fillTime', models.TimeField(auto_now_add=True)),
                ('fillDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='referreldata',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referreldata',
            name='otpStatus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='referreldata',
            name='refrelList',
            field=models.JSONField(default={'listdata': []}),
        ),
    ]
