# Generated by Django 5.0 on 2024-04-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0032_studentbatchesinstractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referreldata',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referreldata',
            name='otpStatus',
            field=models.CharField(default='', max_length=50),
        ),
    ]
