# Generated by Django 5.0 on 2024-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0033_referreldata_otp_referreldata_otpstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCallRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('lastUpdateTime', models.TimeField(auto_now=True)),
                ('lastUpdateDate', models.DateField(auto_now=True)),
                ('fillTime', models.TimeField(auto_now_add=True)),
                ('fillDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentbatchesinstractions',
            name='batchActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentbatchesinstractions',
            name='batchHide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentbatchesinstractions',
            name='batchNameShow',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentbatchesinstractions',
            name='batchPrice',
            field=models.IntegerField(default=0),
        ),
    ]
