# Generated by Django 5.0 on 2024-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0034_studentcallrequestdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatchesinstractions',
            name='batchNameShow',
            field=models.CharField(max_length=50),
        ),
    ]
