# Generated by Django 5.0 on 2024-05-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0032_studentbatchesinstractions_studentcallrequestdata_and_more'),
        ('goobusinessesapp', '0035_alter_studentbatchesinstractions_batchnameshow'),
    ]

    operations = [
    ]
