# Generated by Django 5.0 on 2024-05-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0036_merge_20240504_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatchesinstractions',
            name='batchActive',
        ),
        migrations.RemoveField(
            model_name='studentbatchesinstractions',
            name='batchHide',
        ),
        migrations.RemoveField(
            model_name='studentbatchesinstractions',
            name='batchNameShow',
        ),
        migrations.RemoveField(
            model_name='studentbatchesinstractions',
            name='batchPrice',
        ),
    ]
